# Generated by Django 6.0 on 2026-01-05 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('HACKATHON', 'Hackathon'), ('WEBINAR', 'Webinar'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('OTHER', 'Other')], default='HACKATHON', max_length=20)),
                ('description', models.TextField()),
                ('registration_link', models.URLField(help_text='Link to register for the event')),
                ('date', models.DateTimeField(help_text='When the event starts')),
                ('location', models.CharField(default='Online', help_text='Venue or Online', max_length=200)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
