# Generated by Django 6.0 on 2026-01-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
