# Generated by Django 6.0 on 2026-04-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free Starter'), ('PRO', 'Student Pro'), ('CAREER_READY', 'Career Ready')], default='FREE', max_length=20),
        ),
    ]
