# Generated by Django 6.0 on 2026-04-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_plan',
        ),
    ]
