# Generated by Django 6.0 on 2026-04-14 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userprofile_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('BUNDLE', 'Placement Success Bundle'), ('TUITION', 'Home Tech Tuition')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_tech', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
