# Generated by Django 6.0 on 2026-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
