# Generated by Django 6.0 on 2026-04-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_expires_at_jobposting_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service_type',
            field=models.CharField(choices=[('BUNDLE', 'Placement Success Bundle'), ('TUITION', 'Online Tech Tuition'), ('PROJECT', 'Capstone Project Pro')], max_length=20),
        ),
    ]
