# Generated by Django 6.0 on 2026-04-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicebooking_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='preferred_timing',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='contact_time',
            field=models.CharField(blank=True, help_text='When to contact the student', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_mode',
            field=models.CharField(choices=[('ONE_TIME', 'One-time Payment'), ('EMI', 'EMI Plan')], default='ONE_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='preferred_tech',
            field=models.CharField(blank=True, help_text='Domain / Technology Name', max_length=200, null=True),
        ),
    ]
